# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
superadmin = User.create(email: 'superadmin@examples.com', username: 'superadmin', password: 'pwd12345', name: 'superadmin')

permission1 = Permission.create(module_name: 'User', operation: ['read'].to_json, is_show: false, operation_name: "查看")
permission2 = Permission.create(module_name: 'User', operation: ['new', 'create'].to_json, is_show: false, operation_name: "新增")
permission3 = Permission.create(module_name: 'User', operation: ['update'].to_json, is_show: false, operation_name: "修改")
permission4 = Permission.create(module_name: 'User', operation: ['destroy'].to_json, is_show: false, operation_name: "删除")
permission5 = Permission.create(module_name: 'User', operation: ['permission'].to_json, is_show: false, operation_name: "查看权限管理")
permission6 = Permission.create(module_name: 'Permission', operation: ['new', 'read'].to_json, is_show: false, operation_name: "查看")
permission7 = Permission.create(module_name: 'Permission', operation: ['do_permission'].to_json, is_show: false, operation_name: "设置权限")
permission8 = Permission.create(module_name: 'UserLog', operation: ['read'].to_json, operation_name: "查看")
permission9 = Permission.create(module_name: 'Catalog', operation: ['read'].to_json, operation_name: "查看")
permission10 = Permission.create(module_name: 'Catalog', operation: ['create'].to_json, operation_name: "新增")
permission11 = Permission.create(module_name: 'Catalog', operation: ['update'].to_json, operation_name: "修改")
permission12 = Permission.create(module_name: 'Catalog', operation: ['destroy'].to_json, operation_name: "删除")
permission13 = Permission.create(module_name: 'User', operation: ['to_reset_pwd', 'reset_pwd'].to_json, is_show: false, operation_name: "重置密码")
permission14 = Permission.create(module_name: 'FrontUser', operation: ['read'].to_json, operation_name: "查看")
permission15 = Permission.create(module_name: 'FrontUser', operation: ['update'].to_json, operation_name: "修改")
permission16 = Permission.create(module_name: 'Stamp', operation: ['read'].to_json, operation_name: "查看")
permission17 = Permission.create(module_name: 'Stamp', operation: ['create'].to_json, operation_name: "新增")
permission18 = Permission.create(module_name: 'Stamp', operation: ['update'].to_json, operation_name: "修改")
permission19 = Permission.create(module_name: 'Stamp', operation: ['destroy'].to_json, operation_name: "删除")
permission20 = Permission.create(module_name: 'Stamp', operation: ['to_import', 'import'].to_json, operation_name: "导入")
permission21 = Permission.create(module_name: 'Stamp', operation: ['export'].to_json, operation_name: "导出")
permission16 = Permission.create(module_name: 'Coin', operation: ['read'].to_json, operation_name: "查看")
permission17 = Permission.create(module_name: 'Coin', operation: ['create'].to_json, operation_name: "新增")
permission18 = Permission.create(module_name: 'Coin', operation: ['update'].to_json, operation_name: "修改")
permission19 = Permission.create(module_name: 'Coin', operation: ['destroy'].to_json, operation_name: "删除")
permission20 = Permission.create(module_name: 'Coin', operation: ['to_import', 'import'].to_json, operation_name: "导入")
permission21 = Permission.create(module_name: 'Coin', operation: ['export'].to_json, operation_name: "导出")
permission22 = Permission.create(module_name: 'Bill', operation: ['read'].to_json, operation_name: "查看")
permission23 = Permission.create(module_name: 'Bill', operation: ['create'].to_json, operation_name: "新增")
permission24 = Permission.create(module_name: 'Bill', operation: ['update'].to_json, operation_name: "修改")
permission25 = Permission.create(module_name: 'Bill', operation: ['destroy'].to_json, operation_name: "删除")
permission26 = Permission.create(module_name: 'Bill', operation: ['to_import', 'import'].to_json, operation_name: "导入")
permission27 = Permission.create(module_name: 'Bill', operation: ['export'].to_json, operation_name: "导出")
permission28 = Permission.create(module_name: 'Price', operation: ['read'].to_json, operation_name: "查看")
permission29 = Permission.create(module_name: 'Price', operation: ['create'].to_json, operation_name: "新增")
permission30 = Permission.create(module_name: 'Price', operation: ['update'].to_json, operation_name: "修改")
permission31 = Permission.create(module_name: 'Price', operation: ['destroy'].to_json, operation_name: "删除")
permission32 = Permission.create(module_name: 'Price', operation: ['to_import', 'import'].to_json, operation_name: "导入")
permission33 = Permission.create(module_name: 'Stamp', operation: ['price_import'].to_json, operation_name: "价格导入")
permission34 = Permission.create(module_name: 'Stamp', operation: ['price_export'].to_json, operation_name: "价格导出")
permission35 = Permission.create(module_name: 'Coin', operation: ['price_import'].to_json, operation_name: "价格导入")
permission36 = Permission.create(module_name: 'Coin', operation: ['price_export'].to_json, operation_name: "价格导出")
permission37 = Permission.create(module_name: 'Bill', operation: ['price_import'].to_json, operation_name: "价格导入")
permission38 = Permission.create(module_name: 'Bill', operation: ['price_export'].to_json, operation_name: "价格导出")
permission39 = Permission.create(module_name: 'DicTitle', operation: ['read'].to_json, operation_name: "查看")
permission40 = Permission.create(module_name: 'DicContent', operation: ['read'].to_json, operation_name: "查看")
permission41 = Permission.create(module_name: 'DicContent', operation: ['create'].to_json, operation_name: "新增")
permission42 = Permission.create(module_name: 'DicContent', operation: ['update'].to_json, operation_name: "修改")
permission43 = Permission.create(module_name: 'DicContent', operation: ['destroy'].to_json, operation_name: "删除")
permission44 = Permission.create(module_name: 'ImportFile', operation: ['read'].to_json, operation_name: "查看")
permission45 = Permission.create(module_name: 'ImportFile', operation: ['download'].to_json, operation_name: "下载")
permission46 = Permission.create(module_name: 'Price', operation: ['export'].to_json, operation_name: "导出")

UserPermission1 = UserPermission.create(user_id: superadmin.id, permission_id: permission1.id)
UserPermission2 = UserPermission.create(user_id: superadmin.id, permission_id: permission2.id)
UserPermission3 = UserPermission.create(user_id: superadmin.id, permission_id: permission3.id)
UserPermission4 = UserPermission.create(user_id: superadmin.id, permission_id: permission4.id)
UserPermission5 = UserPermission.create(user_id: superadmin.id, permission_id: permission5.id)
UserPermission6 = UserPermission.create(user_id: superadmin.id, permission_id: permission6.id)
UserPermission7 = UserPermission.create(user_id: superadmin.id, permission_id: permission7.id)
UserPermission8 = UserPermission.create(user_id: superadmin.id, permission_id: permission8.id)
UserPermission9 = UserPermission.create(user_id: superadmin.id, permission_id: permission13.id)


dic_title1 = DicTitle.create(name: "版式", category: "stamp", db_field: "format")
dic_title2 = DicTitle.create(name: "题材", category: "stamp", db_field: "theme")
dic_title3 = DicTitle.create(name: "题材", category: "coin", db_field: "theme")
dic_title4 = DicTitle.create(name: "版别", category: "stamp", db_field: "version")
dic_title5 = DicTitle.create(name: "版别", category: "paper", db_field: "version")
dic_title6 = DicTitle.create(name: "材质", category: "coin", db_field: "material")
dic_title7 = DicTitle.create(name: "重量", category: "coin", db_field: "weight")
dic_title8 = DicTitle.create(name: "年份", category: "coin", db_field: "year")
dic_title9 = DicTitle.create(name: "版刻年号", category: "paper", db_field: "engrave_year")
dic_title10 = DicTitle.create(name: "面值", category: "coin", db_field: "face_value")
dic_title11 = DicTitle.create(name: "面值", category: "paper", db_field: "face_value")
dic_title12 = DicTitle.create(name: "套系(包装规格)", category: "coin", db_field: "pack_spec")
dic_title13 = DicTitle.create(name: "套系(包装规格)", category: "paper", db_field: "pack_spec")
dic_title14 = DicTitle.create(name: "字冠", category: "paper", db_field: "prefix")
dic_title15 = DicTitle.create(name: "字号", category: "paper", db_field: "serial_no")
dic_title15 = DicTitle.create(name: "水印", category: "paper", db_field: "watermark")